# List of Services
services:
  spring:
    build: ./spring   # Look for Dockerfile in this path
    ports:
      - "8080:8080"   # Expose port 8080
    environment:
      # These are used in apllication.property to setup DB connection
      - DB_ADDRESS=jdbc:mysql://mysql:3306
      - DB_DATABASE=template_db
      - DB_USER=root
      - DB_PASSWORD=pwd
    networks:
      - spring-mysql    # Allow the spring app to discover the mysql app
      - spring-react    # Allow the spring app to talk to the react app

  mysql:
    build: ./mysql    # Look for Dockerfile in this path
    environment:
      # Mysql docker image env vars
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=template_db #
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pwd
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - spring-mysql    # Allow the mysql app to talk to the spring app
    
  react:
    build: ./react    # Look for Dockerfile in this path
    ports:
      - "3000:3000"   # Expose port 3000
    environment:
      # Tell the react app that our spring server is running here
      - BACKEND_PROXY=http://spring:8080
    networks:
      - spring-react    # Allow the react app to discover the spring app  

  web-scraper:
    build: ./web-scraper    # Look for Dockerfile in this path
    environment:
      - BACKEND_PROXY=http://spring:8080
      - DB_ADDRESS=jdbc:mysql://mysql:3306
      - DB_DATABASE=template_db
      - DB_USER=root
      - DB_PASSWORD=pwd

    
    networks:
      - spring-mysql    # Allow the web-scraper app to talk to the mysql app
      - spring-react    # Allow the web-scraper app to talk to the react app

volumes:
  mariadb_data:

# List of Networks
networks:               
  spring-mysql:
  spring-react:
