#Docker Compose is a tool for defining and running multi-container Docker applications. 
#With Docker Compose, you use a YAML file to configure your application's services, networks, volumes, and other resources.

version: '3.8'  # Specifies the Docker Compose file version which determines the features available

#This section defines the containers that make up your application. Each service represents a container with its configuration
services:  # Defines the services that make up the application
  swag: #reverse proxy
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=synthix.socs.uoguelph.ca
      - VALIDATION=http
      - STAGING=false #optional
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    depends_on:
      - react
    networks:
      - swag-react
    restart: unless-stopped

  spring:  # The Spring application service
    #Build Context: build: ./spring tells Docker to build an image using the Dockerfile located in the ./spring directory.
    build: ./spring  # Builds the Docker image from the Dockerfile located in the './spring' directory
    #Environment Variables: These are passed to the container at runtime. For example, DB_ADDRESS is set to jdbc:mysql://mysql:3306, indicating the application should connect to a MySQL database at the given JDBC URL.
    environment:  # Environment variables for the Spring application
      - DB_ADDRESS=jdbc:mysql://mysql:3306  # JDBC URL for the MySQL database, 'mysql' is the service name in docker-compose
      - DB_DATABASE=template_db  # The name of the database to use
      - DB_USER=root  # The username for the database
      - DB_PASSWORD=pwd  # The password for the database
    #Networks: The service is attached to spring-mysql and spring-react networks, enabling network communication with the MySQL and React services.
    networks:  # Networks the Spring service is connected to
      - spring-mysql  # Network for communicating with MySQL
      - spring-react  # Network for communicating with the React service

  mysql:  # The MySQL database service
    build: ./mysql  # Builds the Docker image from the Dockerfile in the './mysql' directory
    #Environment Variables: Used to configure the MySQL server, like setting the root password (MYSQL_ROOT_PASSWORD) and specifying the database to create at startup (MYSQL_DATABASE).
    environment:  # Environment variables for the MySQL service
      - MYSQL_ROOT_PASSWORD=pwd  # The root password for MySQL
      - MYSQL_DATABASE=template_db  # The database to create when the container starts
    #Volumes:  mariadb_data:/var/lib/mysql mounts the named volume mariadb_data to /var/lib/mysql inside the container, providing persistent storage for the database.
    volumes:  # Persistent storage for the MySQL database
      - mariadb_data:/var/lib/mysql  # Maps 'mariadb_data' volume to the data directory of MySQL
    networks:  # Network the MySQL service is connected to
      - spring-mysql  # Network for communicating with the Spring service
 
  react:  # The React frontend service
    build: ./react  # Builds the Docker image from the Dockerfile in the './react' directory
    environment:  # Environment variable for the React service
      - BACKEND_PROXY=http://spring:8080  # The URL to the backend Spring service
    networks:  # Network the React service is connected to
      - spring-react  # Network for communicating with the Spring service
      - swag-react

  web-scraper:  # The Python application service
    build: ./web-scraper  # Builds the Docker image from the Dockerfile in the './web-scraper' directory
    environment:  # Environment variables for the Python service
      - DB_HOST=mysql  # Hostname for the MySQL database, 'mysql' is the service name in docker-compose
      - DB_DATABASE=template_db  # The name of the database to use
      - DB_USER=root  # The username for the database
      - DB_PASSWORD=pwd  # The password for the database
    depends_on:
      - mysql  # Ensures MySQL service is started before the Python service
    networks:
      - spring-mysql  # Connects to the same network as MySQL for communication

volumes:
  mariadb_data:  # Defines a named volume 'mariadb_data' for the MySQL service to use for data persistence

networks:  # Defines the networks used by the services
  spring-mysql:  # Network used by the Spring and MySQL services
  spring-react:  # Network used by the Spring and React services
  swag-react: #Network used by the Swag and React services
